[package]
edition = "2018"
name = "libstardustxr-rs"
version = "0.9.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-rs = "0.6.1"
flatbuffers = "2.1.2"
flexbuffers = "2.0.0"
mint = "0.5.9"
nanoid = "0.4.0"
schemas = {path = "schemas"}
thiserror = "1.0.31"
uds = "0.2.6"
xdg = "2.4.1"
