[workspace]
resolver = "2"
members = ["wire", "fusion", "protocol", "gluon"]
package.version = "0.50.0"
package.repository = "https://github.com/StardustXR/core/"
package.homepage = "https://stardustxr.org"
package.license = "MIT"
